### ISSUE TITLE
Avoid brute force by locking out after failed login attempts

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-u2f-authenticator#1]
Similar issue as in the TOTP module, although a lot harder to achieve with the PKI challenges involved. https://github.com/elliot-sawyer/totp-authenticator/issues/13. Just to be on the safe side, really

**Comment by brynwhyman** [comment]
Yeah, as with the TOTP module, I'd be interested to know if this functionality can exist on the boostrapmfa module and be consumed by each authenticator module;
https://github.com/elliot-sawyer/totp-authenticator/issues/13#issuecomment-436097007

**Comment by brynwhyman** [comment]
Closed for https://github.com/silverstripe/silverstripe-mfa/issues/47
